#!/bin/bash

echo "🧪 Test de Persistencia de Sesión - El Súper Gestor"
echo "================================================="
echo ""

echo "🔍 PASO 1: Verificando que el servidor esté corriendo..."
if curl -s http://localhost:3000/health > /dev/null 2>&1; then
    echo "✅ Servidor backend funcionando en puerto 3000"
else
    echo "❌ ATENCIÓN: Servidor backend no responde en puerto 3000"
    echo "   Asegúrate de que el servidor backend esté ejecutándose"
    echo ""
fi

echo ""
echo "📋 INSTRUCCIONES PARA PROBAR LA PERSISTENCIA:"
echo "=============================================="
echo ""
echo "1. 🌐 Abre http://localhost:5174 en tu navegador"
echo ""
echo "2. 🔑 Haz login con uno de estos usuarios:"
echo "   • admin123 / supersegura (Admin)"
echo "   • testuser / 123456 (Metahumano)"
echo "   • burocrata1 / tramite123 (Burócrata)"
echo ""
echo "3. ✅ Verifica que el login funciona y te redirige al dashboard correcto"
echo ""
echo "4. 🔄 RECARGA LA PÁGINA (F5 o Ctrl+R)"
echo ""
echo "5. 🎯 RESULTADO ESPERADO:"
echo "   • La sesión debe mantenerse"
echo "   • Debes seguir en tu dashboard (NO redirigido al login)"
echo "   • El botón debe mostrar 'Cerrar Sesión' en lugar de 'Login'"
echo ""
echo "6. 🚪 Haz clic en 'Cerrar Sesión'"
echo ""
echo "7. 🎯 RESULTADO ESPERADO:"
echo "   • Debe redirigirte a la página principal (/)"
echo "   • El botón debe mostrar 'Login'"
echo "   • Si recargas, NO debe volver a loguearte automáticamente"
echo ""
echo "8. 🔐 Intenta acceder manualmente a rutas protegidas:"
echo "   • http://localhost:5174/homeAdmin"
echo "   • http://localhost:5174/homeMeta"
echo "   • http://localhost:5174/homeBurocrata"
echo ""
echo "9. 🎯 RESULTADO ESPERADO:"
echo "   • Debe redirigirte automáticamente a /login"
echo ""
echo "💡 FUNCIONALIDADES IMPLEMENTADAS:"
echo "================================="
echo "✅ Persistencia de sesión en localStorage"
echo "✅ Recuperación automática al recargar página"
echo "✅ Logout completo (limpia localStorage)"
echo "✅ Rutas protegidas con validación de roles"
echo "✅ Redirección automática según estado de autenticación"
echo "✅ Login en SidebarUser redirige a /login (no modal)"
echo "✅ Logout funcional en todos los sidebars"
echo ""
echo "🐛 SI ALGO NO FUNCIONA:"
echo "======================="
echo "• Abre DevTools (F12) → Console para ver logs detallados"
echo "• Verifica Application → Local Storage para ver datos persistidos"
echo "• Comprueba que el servidor backend esté funcionando"
echo ""
echo "🎉 ¡La persistencia de sesión está implementada!"
